# Generated by Django 5.0 on 2025-02-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blog_blog_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='blogs',
        ),
    ]
