# Generated by Django 5.0 on 2025-02-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_blog_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='created_At',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
