# Generated by Django 5.0 on 2025-02-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_blogs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='created_At',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
