# Generated by Django 5.0 on 2025-02-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_blogs_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_comment',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
