# Generated by Django 5.0 on 2025-02-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_blog_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_comment',
            name='time',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
