# Generated by Django 5.0 on 2025-02-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_blog_comment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_comment',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog_comment',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
