# Generated by Django 5.0 on 2025-02-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_con_services_it_services_services_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='con_services',
            name='image',
            field=models.ImageField(default=True, upload_to='mat_services/'),
        ),
    ]
