# Generated by Django 5.0 on 2025-02-10 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_con_services_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='img_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=True, upload_to='about_us/')),
                ('alt', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('a_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_us', to='home.about_us')),
            ],
        ),
    ]
