# Generated by Django 5.0 on 2025-02-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_about_us_img_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='image',
            field=models.ImageField(default=True, upload_to='about_us/'),
        ),
        migrations.DeleteModel(
            name='img_about',
        ),
    ]
