# Generated by Django 5.0 on 2025-02-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand_logo',
            name='image',
            field=models.ImageField(default=True, upload_to='brand_logo/'),
        ),
    ]
