# Generated by Django 5.0 on 2025-02-11 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_website'),
    ]

    operations = [
        migrations.DeleteModel(
            name='website',
        ),
    ]
