# Generated by Django 5.0 on 2025-02-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_about_us_created_at_address_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('whatsapp', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
